"""Validate a host-private app.local.toml without printing secret values."""

import base64
import binascii
import sys
import tomllib
from pathlib import Path
from urllib.parse import urlsplit


FERNET_KEYS = (
    "customer_access_token_encryption_key",
    "model_connection_secret_encryption_key",
    "lark_config_encryption_key",
)


def is_fernet_key(value: object) -> bool:
    if not isinstance(value, str):
        return False
    try:
        return len(base64.urlsafe_b64decode(value.encode("ascii"))) == 32
    except (ValueError, UnicodeEncodeError, binascii.Error):
        return False


def is_allowed_origin(value: object, app_env: object) -> bool:
    if not isinstance(value, str):
        return False
    parsed = urlsplit(value)
    loopback_preprod = (
        app_env == "preproduction"
        and parsed.scheme == "http"
        and parsed.hostname in {"localhost", "127.0.0.1", "::1"}
    )
    return bool(
        (parsed.scheme == "https" or loopback_preprod)
        and parsed.netloc
        and parsed.path in {"", "/"}
        and not parsed.username
        and not parsed.password
        and not parsed.query
        and not parsed.fragment
    )


def main() -> None:
    path = Path(sys.argv[1] if len(sys.argv) == 2 else "backend/config/app.toml")
    try:
        with path.open("rb") as file:
            values = tomllib.load(file)
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise SystemExit(f"Invalid private configuration: {error}") from error

    failures: list[str] = []
    for key in FERNET_KEYS:
        value = values.get(key)
        if value not in (None, "") and not is_fernet_key(value):
            failures.append(f"{key} must be a Fernet key generated by deploy/generate-production-secrets.py")
    auth_secret = values.get("auth_session_secret")
    if auth_secret not in (None, "") and (not isinstance(auth_secret, str) or len(auth_secret.encode()) < 32):
        failures.append("auth_session_secret must contain at least 32 bytes")
    admin_password = values.get("initial_admin_password")
    if admin_password not in (None, "") and (not isinstance(admin_password, str) or len(admin_password) < 16):
        failures.append("initial_admin_password must contain at least 16 characters")
    for key in ("customer_frontend_base_url", "admin_frontend_base_url"):
        if not is_allowed_origin(values.get(key), values.get("app_env")):
            failures.append(f"{key} must be an allowed origin without a path, query, or fragment")

    if failures:
        raise SystemExit("Production configuration rejected:\n- " + "\n- ".join(failures))
    print(f"Production private configuration is valid: {path}")


if __name__ == "__main__":
    main()
